reviewers:
  defaults:
    - core
  groups:
    core:
      - team:core
files:
  '.github/**':
    - MSevey
    - core
options:
  ignore_draft: true
  ignored_keywords:
    - WIP
  number_of_reviewers: 3
