run:
  timeout: 5m
  modules-download-mode: readonly
  # mempool and indexer code is borrowed from Tendermint
  skip-dirs:
    - mempool
    - state/indexer
    - state/txindex

linters:
  enable:
    - deadcode
    - errcheck
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - revive
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck

issues:
  exclude-use-default: false
  include:
    - EXC0012  # EXC0012 revive: Annoying issue about not having a comment.
    - EXC0014  # EXC0014 revive: Annoying issue about not having a comment.

linters-settings:
  revive:
    rules:
      - name: package-comments
        disabled: true
      - name: duplicated-imports
        severity: warning
      - name: exported
        arguments:
          - disableStutteringCheck

  goimports:
    local-prefixes: github.com/rollkit
