# lint runs all linters in this repository
# This workflow is triggered by ci_release.yml workflow
name: lint
on:
  workflow_call:
    inputs:
      GO_VERSION:
        description: 'Go version to use'
        type: string
        required: true

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ inputs.GO_VERSION }}
        # This steps sets the GIT_DIFF environment variable to true
        # if files defined in PATTERS changed
      - uses: technote-space/get-diff-action@v6.1.2
        with:
          # This job will pass without running if go.mod, go.sum, and *.go
          # wasn't modified.
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - uses: golangci/golangci-lint-action@v3.7.0
        with:
          version: latest
          args: --timeout 10m
          github-token: ${{ secrets.github_token }}
        if: env.GIT_DIFF

  # hadolint lints the Dockerfile
  hadolint:
    uses: rollkit/.github/.github/workflows/reusable_dockerfile_lint.yml@v0.2.2 # yamllint disable-line rule:line-length
    with:
      dockerfile: docker/mockserv.Dockerfile

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rollkit/.github/.github/actions/yamllint@v0.2.2

  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rollkit/.github/.github/actions/markdown-lint@v0.2.2

  protobuf-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - run: make proto-gen
      - run: make proto-lint
